theme: jekyll-theme-cayman
title: Coarse Temporal Attention Network (CTA-Net) for Driver's Activity Recognition
description: Zachary Wharton, Ardhendu Behera, Yonghuai Liu and Nik Bessis
github:
  is_project_page: false
